language: bash
sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_73c7cac50e50_key -iv $encrypted_73c7cac50e50_iv
  -in .travis/khs1994-robot.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
# - echo "TZ='Asia/Shanghai'; export TZ" >> ~/.profile
# - ". ~/.profile"
- sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai  /etc/localtime
- date
- git config --global user.name "khs1994-merge-robot"
- git config --global user.email "ai@khs1994.com"
- docker pull khs1994/gitbook:1.0.0
script:
- cd ~
- export REPO=$REPO
- export REPO_ALIYUN=$REPO_ALIYUN
- "~/build/khs1994-website/docs/.travis/deploy.sh"
- cd ~
env:
  global:
  - DEPLOY_BRANCH: gh-pages
  - REPO: git@github.com:khs1994-website/docs.git
  - REPO_ALIYUN: git@code.aliyun.com:khs1994-website/docs.git
addons:
  ssh_known_hosts:
  - code.aliyun.com
  - github.com
branches:
  only:
  - master
  - gitbook
